pion/transport

- test/util.go
Looking at the history of this function, originally the final count was compared against an intiail count instead of 0. should we reinstate the initial count to prevent test cross-contamination?
> Reinstate initial goroutine check

- test/util.go
- test/util_test.go
Repeat CheckRoutines to reduce flakiness while not blocking
for longer than needed. The routines are now checked every
200ms for a maximum of 10s.
> Repeat CheckRoutines to reduce flakiness

- .golangci.yml
- test/bridge.go
- test/bridge_test.go
Added connection bridge test used by new sctp and datachannel tests. Typical usage is to connect two SCTP endpoints with this bridge. The bridge allows you to drop, reorder packets as needed.
This relates to pions/webrtc#334
> Connection bridge tool

- go.mod
- go.sum
- packetio/buffer.go
- packetio/buffer_test.go
We're not able to use `bytes.Buffer` because it would combine multiple
Writes into a single Read. `packetio.Buffer` provides a similar but is
designed to work with packets, avoiding this situation.
There are similar buffers implemented separarely in webrtc/srtp/ice/mux.
These used channels and were too slow to keep up with the read loop. I
wrote a benchmark for comparison:
```
name                   old time/op    new time/op     delta
BenchmarkBuffer14-8       859ns ± 5%      129ns ± 4%   -84.93%
BenchmarkBuffer140-8      832ns ± 4%      154ns ± 4%   -81.43%
BenchmarkBuffer1400-8     825ns ± 8%      351ns ± 4%   -57.49%
name                   old speed      new speed       delta
BenchmarkBuffer14-8    16.3MB/s ± 5%  107.8MB/s ± 3%  +561.08%
BenchmarkBuffer140-8    168MB/s ± 4%    904MB/s …
```
> Add packetio interface for network buffering

- vnet/README.md
- vnet/conn.go
- vnet/conn_map.go
- vnet/conn_map_test.go
- vnet/conn_test.go
- vnet/nat.go
- vnet/nat_test.go
- vnet/net.go
- vnet/net_native_test.go
- vnet/net_test.go
See issue #15 for details
I am working on adding vnet support to pion/turn.
With these fixes, I was able to pass a new test using vnet to test communciation between TURN server and client via a virtually hosted NAT.
> Allow listening on 0.0.0.0:x

- vnet/conn.go
- vnet/nat.go
- vnet/nat_test.go
- vnet/net.go
Fixes #20
This is to align the behavior of ListenUDP() and DialUDP() methods with that of net package.
Also, improved a debug log message.
> Allow nill laddr for ListenUDP and DialUDP

- vnet/chunk.go
- vnet/nat.go
- vnet/router.go
During the debugging for pion/ice#46, I found the improved logs in this PR had made the debugging much easier.
* Log router names (auto-assigned, also configurable)
* Improved NAT binding-related messages (new binding, how addresses are translated, etc)
* Add a unique (base36) tag for each chunks to track how a particular chunk was routed)
```
[router3] route udp chunk 3q 10.2.0.1:5300 => 27.1.1.1:49152
```
> `route3` is the name of the router
> `3q` is the unique tag for the chunk
```
[router3] created a new NAT binding oKey=udp:10.2.0.1:5089:1.2.3.4:5495 iKey=udp:28.1.1.1:49158:1.2.3.4:5495
[router2] translate outbound chunk from udp chunk n 192.168.0.1:5318 => 10.2.0.1:5456 to udp chunk n 27.1.1.1:49154 => 10.2.0.1:5456
[router2] translate inbound chunk from udp chunk p 1.2.3.4:3478 => …
```
> vnet: Improve log messages

- vnet/conn.go
- vnet/net.go
- vnet/resolver.go
- vnet/router.go
- vnet/stress_test.go
Fixes #25 
I went over all the code and found other potential dead-locks or race conditions, but the cause of occasional stalling of pion/turn test was the child router call into the parent call holding its own mutex.
I have confirmed pion/turn test no longer stalls with this branch.
Also, I have added a stress test running 20 (goroutines) performing ping/pong tests.
> Fix deadlock

- vnet/net.go
- vnet/net_native_test.go
- vnet/net_test.go
- vnet/router.go
- vnet/router_test.go
- vnet/stress_test.go
Resolves #32
See #32 for details.
> Allow more than one static IP addresses

- vnet/nat.go
- vnet/nat_test.go
- vnet/router.go
- vnet/router_test.go
Relates to pion/webrtc#835
Added 1:1 DNAT behavior.
Tested with PR at pion/ice#103
> Support 1:1 NAT behavior

- test/util.go
This helps us track down when other tests are leaking
> Also no leaks on start in CheckRoutines

- .golangci.yml
- .travis.yml
- README.md
- packetio/buffer.go
- test/bridge_test.go
- test/stress.go
- test/util.go
- vnet/router_test.go
- vnet/stress_test.go
- vnet/vnet.go
Fix whitespace and stylecheck error.
Disable godox.
preparing pion/.goassets#4
> Upgrade golangci-lint to 1.19.1

- vnet/net_native_test.go
Some tests using net.Conn connection are disabled for now
as it is not fully supported by WASM MVP stage.
preparation for https://github.com/pion/.goassets/pull/4
> Support WASM build/test

- vnet/net_native_test.go
Debian based linux uses 127.0.1.1 as a local loopback address
in some condition of the install.
Fix #51
ref: https://github.com/pion/transport/pull/49
> Fix TestNetNative on Debian

- test/util.go
- test/util_nowasm.go
- test/util_wasm.go
Nested t.Run on Go 1.14 WASM has runtime.goexit() routine at beginning.
https://github.com/pion/.goassets/pull/15
https://github.com/pion/webrtc/pull/1066
> Support Go 1.14 WASM

- README.md
- packetio/buffer.go
- packetio/buffer_test.go
This more than doubles the performance of the current (highly unrealistic) benchmark, and reduces allocation to virtually nothing.  There are some minor API changes, described in the commit messages.
```
name          old time/op    new time/op    delta
Buffer14-4       552ns ± 8%     176ns ± 2%   -68.10%  (p=0.000 n=8+8)
Buffer140-4      435ns ± 5%     227ns ± 2%   -47.81%  (p=0.000 n=8+8)
Buffer1400-4     929ns ± 3%     385ns ± 2%   -58.55%  (p=0.000 n=8+8)
name          old speed      new speed      delta
Buffer14-4    25.4MB/s ± 8%  79.5MB/s ± 2%  +212.67%  (p=0.000 n=8+8)
Buffer140-4    322MB/s ± 5%   617MB/s ± 2%   +91.49%  (p=0.000 n=8+8)
Buffer1400-4  1.51GB/s ± 3%  3.64GB/s ± 2%  +141.27%  (p=0.000 n=8+8)
name          old alloc/op   new alloc/op   delta
Buffer14-4        138B ± …
```
> Optimise packetio.Buffer by using a circular buffer

- packetio/buffer_test.go
Which was introduced by https://github.com/pion/transport/pull/72.
> Discard unparam lint error

- packetio/buffer.go
- packetio/buffer_test.go
- packetio/hardlimit.go
- packetio/no_hardlimit.go
It avoids discarding user config without returning error.
4MB hardcoded limit is used if user doesn't call `SetLimitSize` or set to zero.
Hardlimit can be enabled by setting `packetioSizeHardlimit` build tag.
https://github.com/pion/transport/pull/72#discussion_r435727183
> Respect user's SetLimitSize value

- test/test_test.go
Stress test requires that the connection never drops a packet.
UDP stream is not suitable to be tested by this.
Fixes #105
> Fix test/BenchmarkUDP

- packetio/buffer.go
- packetio/buffer_test.go
Read/Write overhead is increased a little bit,
but Read/WriteContext is faster than Read/Write.
version        | iter     | op         | bw
-------------- | -------- | ---------- | ---
Old            | 19459795 | 61.1 ns/op | 229.30 MB/s
New NoContext  | 17973650 | 67.2 ns/op | 208.40 MB/s
New Context    | 30738019 | 39.1 ns/op | 358.17 MB/s
version        | iter     | op         | bw
-------------- | -------- | ---------- | ---
Old            | 17757152 | 68.1 ns/op | 2056.79 MB/s
New NoContext  | 16810936 | 71.5 ns/op | 1957.94 MB/s
New Context    | 24479403 | 48.6 ns/op | 2883.21 MB/s
version        | iter     | op         | bw
-------------- | -------- | ---------- | ---
Old            | 13673950 | 86.7 ns/op | 16147.15 MB/s
New NoContext  | 13727745 | 86.8 ns/op | 16133.11 MB/s
New …
> Add ReadContext/WriteContext

- connctx/connctx.go
- connctx/connctx_test.go
- connctx/pipe.go
It will be used by the test in srtp package to migrate to `packetio.ReadContext/WriteContext`.
> Move ConnCtx from dtls package

- packetio/buffer.go
- packetio/buffer_test.go
This change caused a ~24% performance decrease
Relates to pion/webrtc#1564
This reverts the following commits
* 26e171fd80cada79f0f2172bd96c2b98662455d8
> Revert adding Context to public API

- vnet/udpproxy_direct.go
- vnet/udpproxy_direct_test.go
It allows user to simulate the REPLAY ATTACK,
by delivering duplicated packet to server,
or simulate the network delay and ARQ packet.
> Support directly deliver packet to UDPProxy

- AUTHORS.txt
- vnet/tbf.go
- vnet/tbf_test.go
This PR adds an alternative proposal for additional network conditioning to #141 . Instead of adding the network condition to a specific `Net` or `Router`, it adds a filter that embeds a `NIC`. That way, the filter can wrap any `Net` before being passed to a router, to simulate a bandwidth limit on the link from the `Router` to the `Net`.
The filter implemented here is just a very simple form of a Token Bucket Filter, which drops all incoming packets when no tokens are available. A later improvement might add some better queuing behavior.
I think similar filters could be used to implement other kinds of network conditioning like latency and different filters could be combined to provide presets for different environments.
@Antonito @Sean-Der @enobufs What do you think about this approach? …
> Add Token Bucket Filter for bandwidth limitation

- vnet/router.go
- vnet/router_test.go
This allows the user to connect two routers, without setting the NIC. This is necessary when setting up the NIC manually, to wrap the child router's NIC in another type, e.g. the TokenBucketFilter to apply some simulated network condition.
Without this, we can only simulate network conditions between `Net` and `Router`, but not between two `Router`.
> Expose AddChildRouter for network conditioning between routers

- examples/vnet-udpproxy/README
- net.go
- stdnet/net_test.go
- vnet/net.go
- vnet/net_test.go
- vnet/router.go
- vnet/router_test.go
- vnet/stress_test.go
In order to align our `transport.Interface` wrapper more closely to Go's `net.Interface` type.
> Rename Interface.Addresses() to Interface.Addrs()

- vnet/tbf.go
- vnet/tbf_test.go
This avoids continuously updating the token count, even if no new chunks
arrive. It also updates some default values and uses floats to calculate
the tokens, which makes it more accurate.
> Make TBF refill only when new chunks arrive

- udp/conn.go
- udp/conn_test.go
Fixes https://github.com/pion/udp/issues/91
> Merge github.com/pion/udp into github.com/pion/transport

- packetio/buffer.go
- packetio/buffer_test.go
If StrictDeadline option is set to false (default), Read() may return data even if the deadline is exceeded or context is canceled. It may increases the performance.
Set true to make Buffer behaves more like net.Conn.
This also restore improved test reverted by ac22c334.
Related #116
> Add StrictDeadline option to packetio.Buffer

- dpipe/dpipe.go
- dpipe/dpipe_test.go
> Add pion/dtls/internal/net/dpipe package

- connctx/connctx_test.go
- Fix typo in TestReadTimeout
- Add benchmarks for connctx
```
goos: linux
goarch: amd64
pkg: github.com/pion/transport/v2/connctx
cpu: Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
BenchmarkBase-8    	  956014	      1324 ns/op	3094.11 MB/s	       0 B/op	       0 allocs/op
BenchmarkWrite-8   	  399874	      2559 ns/op	1600.41 MB/s	     192 B/op	       4 allocs/op
BenchmarkRead-8    	  520050	      2319 ns/op	1766.26 MB/s	     192 B/op	       4 allocs/op
PASS
ok  	github.com/pion/transport/v2/connctx	4.742s
```
> connctx benchmarks

- AUTHORS.txt
- udp/conn.go
Notify read error if udp.listener.readloop exit,
also fix #238 
If listener.readloop encounter an error and exit, the accept will never return as no connection is created.
Fixes #...
> Notify read error if udp.listener.readloop exit

- replaydetector/replaydetector.go
- replaydetector/replaydetector_test.go
Updates the replay detector interface and implementations to support
indicating whether the accepted packet resulted in an update of the
latest sequence number.
Note: this is not a breaking change as the accept() callback was
previously returning zero values and is now returning one, which can be
ignored if desired. It may cause linter failures in some consumers if
using a strict policy.
Signed-off-by: Daniel Mangum <georgedanielmangum@gmail.com>
See https://github.com/pion/dtls/pull/558#discussion_r1280695149 for motivation.
> feat: add latest sequence number notify to replaydetector

- udp/batchconn.go
- udp/conn.go
- udp/conn_test.go
In case of high throughput that the sfu serves massive audio tracks, the syscall of every single udp.Write will become the largest consumer of cpu time and reduce the throughput. This PR add batch io option to udp listener so the sfu can use udp mux + batch io to merge the syscall to be more efficient. In [livekit](https://github.com/livekit/livekit) sfu performance test, the udp mux with batch io improves nearly 100% forwarding throughput compared to normal config(no udp mux).
> Add batch read/write for udp listener

- AUTHORS.txt
- dpipe/dpipe.go
- examples/vnet-udpproxy/main.go
- go.mod
- packetio/buffer.go
- replaydetector/replaydetector.go
- replaydetector/replaydetector_test.go
- stdnet/net.go
- test/bridge.go
- test/stress.go
- udp/conn.go
- udp/conn_test.go
- vnet/conn.go
- vnet/loss_filter_test.go
- vnet/net.go
- vnet/net_test.go
- vnet/router.go
- vnet/stress_test.go
To support replaydetector API changes
Relates to https://github.com/pion/transport/issues/264
> Start pion/transport@v3

- deadline/deadline.go
- deadline/deadline_test.go
- deadline/timer.go
- deadline/timer_generic.go
- deadline/timer_js.go
- packetio/buffer_test.go
before
```
BenchmarkDeadline/Set-10         	 1535445	       784.3 ns/op	     456 B/op	       6 allocs/op
```
after
```
BenchmarkDeadline/Set-10         	13248633	        79.64 ns/op	       0 B/op	       0 allocs/op
```
> Reuse timer in Deadline

- go.mod
- go.sum
- stdnet/net.go
- stdnet/net_test.go
using a wrapper of net package to support android 11
Fixes
> android 11 suppored

- packetio/buffer.go
- packetio/buffer_test.go
This changes Close from being a "signaler" to a "broadcaster" of the notify condition. There's a small, but possible chance that between `Unlock` and `select` at the bottom of `Read` that we will have concurrent reads in the same position which means only once can receive a notify. If a `Close` happens in between this time, one or more reads will be blocked. One such case where this happen is for an srtp and srtcp reader.
In a simpler case, one read in the same position may miss a notify event during a Close. This affects any basic use of a *packetio.Buffer.
Fixes #298 and #299 (maybe)
I reproduced this with synchronization points at the critical point mentioned such that we start 2 reads, close before the select, and then continue the reads, at which point the test will time out. The new …
> Broadcast notify on Buffer.Close

- packetio/buffer.go
- packetio/buffer_test.go
Buffer's usage of `waiting` causes a scenario where if two reads come in while a write is happening can cause waiting to be stuck in false and all write "signals" will be dropped. After reading through the code, I can't figure out why the waiting condition is necessary; the worst thing I can imagine is we don't send to the buffered channel as often.
Fixes #299
> Remove buffer waiting condition

- packetio/buffer.go
> Remove unused waiting field

- .golangci.yml
- connctx/connctx_test.go
- deadline/deadline_test.go
- dpipe/dpipe_test.go
- netctx/conn_test.go
- netctx/packetconn_test.go
- packetio/buffer_test.go
- replaydetector/replaydetector_test.go
- test/bridge.go
- test/bridge_test.go
- test/test_test.go
- test/util_test.go
- udp/conn_test.go
- utils/xor/xor_test.go
- vnet/conn_map_test.go
- vnet/loss_filter.go
- vnet/nat_test.go
- vnet/net_test.go
- vnet/udpproxy_direct_test.go
- vnet/udpproxy_test.go
Use testify's assert package instead of the standard library's testing package.
https://github.com/pion/.goassets/pull/222
> Update lint rules, force testify/assert for tests

- replaydetector/replaydetector.go
- replaydetector/replaydetector_test.go
Fixes the accept() callback of wrappedSlidingWindowDetector to update mask correctly when the sequence number wraps between seq and latestSeq. Without this fix some packets that should be blocked may be let through around sequence number wrap arounds, as demonstrated by the added test case.
> Handle replay after wrapping in replaydetector

- vnet/tbf.go
This fixes a race condition on concurrent reads/writes on the `t.rate` field.
> Include all reads in lock

- vnet/delay_filter.go
- vnet/delay_filter_test.go
- vnet/loss_filter.go
- vnet/loss_filter_test.go
Implement DelayFilter and LossFilter for vnet package to enable dynamic network condition simulation during runtime:
DelayFilter features:
* Atomic delay adjustment with SetDelay() method
* Automatic startup with background processing
* Thread-safe delay changes without blocking
* Graceful shutdown with packet draining
LossFilter features:
* Multiple loss handler strategies (Random, Shuffle)
* Runtime loss rate adjustment with SetLossRate()
* Immediate or gradual rate change options
* Deterministic vs random loss patterns.
* Unit tests
> Add dynamic loss and delay filters with runtime controls
