- .github/assert-contributors.sh
- .github/hooks/commit-msg.sh
- .github/hooks/pre-commit.sh
- .github/hooks/pre-push.sh
- .github/install-hooks.sh
- .github/lint-commit-message.sh
- .golangci.yml
- .travis.yml
- LICENSE
- README.md
- test/util.go
> CI: Setup CI

- README.md
- go.mod
> Add module support

- test/bridge.go
lossChance lets us simulate packet loss using brideConn, this is useful
for testing DTLS. But could also be useful for testing other things in
the future
> Add lossChance to bridge

- test/bridge.go
- test/bridge_test.go
I'd like to add a new method to Bridge for retransmission testing for SCTP.
Relates to pions/sctp#24
> [WIP] Added DropNextNWrites to bridge

- README.md
- go.mod
Pions organization was renamed to pion
> Mass replace pions -> pion

- test/bridge.go
> Filter for bridge

- vnet/README.md
- vnet/net.go
- vnet/net_native_test.go
- vnet/net_test.go
See #15 for details
@hugoArregui 
This fix should let pion/ice#46 move forward.
> Added ResolveUDPAddr()

- vnet/conn_map.go
- vnet/net.go
Added mutex protection for udpConnMap.
(Confirmed no more race in the new pion/turn test)
> Protect udpConnMap with mutex

- vnet/chunk.go
- vnet/chunk_test.go
- vnet/net.go
- vnet/net_native_test.go
- vnet/net_test.go
- vnet/router.go
- vnet/router_test.go
* Added a method AddChunkFilter to Router class
* Added a method Tag() to Chunk interface
* Added a method IsVirtual() to Net class
Resolves #28
> AddChunkFilter

- go.mod
- go.sum
- vnet/router.go
- vnet/router_test.go
* Added following parameters to RouterConfig
- MinDelay
- MaxJitter
* Added a test for delay feature
* Resolves #30
> Introduce configurable delay

- packetio/buffer.go
> Better error message when packetio.Buffer is full

- .golangci.yml
- .travis.yml
- vnet/nat.go
- vnet/nat_test.go
- vnet/resolver_test.go
Fixes #36 
Not only MappingBehavior param was not used, but also the original code also had some mix-up between mapping and filtering keys and there was no test to detect that.
The changes fix above with additional test that confirms that mapping parameter works as expected and filtering behavior issue has been fixed.
> Fixed NAT binding and filtering logic

- test/util.go
Add nolint comment.
ref: https://github.com/pion/transport/pull/49#issuecomment-573610609
> Allow panic in test util

- replaydetector/replaydetector.go
- replaydetector/replaydetector_test.go
Add test case and fix old sequence number check condition.
> Fix replaydetector's edge case

- replaydetector/replaydetector.go
- replaydetector/replaydetector_test.go
Add wrapped version of ReplayDetector which is required in SRTP.
> Add wrapped ReplayDetector

- vnet/conn.go
- vnet/conn_test.go
Fix unsafe chan usage.
Fixes #76
Fixes https://github.com/pion/ice/issues/219
> VNet: fix race during UDPConn.Close

- connctx/connctx.go
- test/connctx.go
- test/stress.go
> Support ConnCtx in Stress test

- test/bridge_test.go
- fix data race
- make sure conns are actually closed
Fixes #113
> Fix test.Bridge test stability

- packetio/buffer.go
- packetio/errors.go
Allow users to use wrapped errors
> Expose ErrTimeout

- README.md
- packetio/buffer.go
Helpers to identify buffer type in buffer factory.
> Add buffer packet protocol type

- vnet/udpproxy.go
1. Stop all proxy workers when close UDPProxy.
2. Use context to notify and wait for all workers to quit.
3. When context is done, close all UDPConn.
> Do cleanup when close UDPProxy

- vnet/loss_filter.go
- vnet/loss_filter_test.go
The filter drops every packet with a fixed probability.
> Implement a simple packet loss simulation

- AUTHORS.txt
- connctx/connctx.go
Fixes https://github.com/pion/dtls/issues/390
> Fix deadlock in connctx.WriteContext

- AUTHORS.txt
- test/bridge.go
> Fix invalid getter in test/bridge.go
